apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: ""
    # each person must use the nodeSelector value from options given below:

    # infra1, 
    # infra2, 
    # node-databas1,
    # node-verksamhet1

    openshift.io/node-selector: "infra1"
  name: NAMESPACE