---
# Source: prometheus-operator/templates/prometheus-operator/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: stakater-monitoring
  namespace: NAMESPACE
  labels:
    app: stakater-operator
    
imagePullSecrets:
  []
  
