---
# Source: influxdb/templates/init-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "influxdb-init"
  namespace: storage
  labels:
    app: "influxdb"
data:
  init.iql: CREATE DATABASE "prometheus"
  