---
# Source: influxdb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "influxdb"
  namespace: "storage"
  labels:
    app: "influxdb"
    chart: "influxdb-3.0.1"
    release: "influxdb"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 8086
    targetPort: 8086
  - name: rpc
    port: 8088
    targetPort: 8088
  selector:
    app: influxdb
