{
 "title": "Catalog Service",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(count_requests_total{}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "No of products",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "product_count{pod=\"$instance\"}",
     "legendFormat": "Total Product Count"
    }
   ]
  },
  {
   "title": "Total API Requests",
   "type": "graph",
   "description": "Shows the count of total emails sent by the pod overtime.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " count_requests_total{pod=\"$instance\"}",
     "legendFormat": "API Request Count"
    }
   ]
  },
  {
   "title": "Get all Products",
   "type": "graph",
   "description": "Keeps track of seconds consumed by com.carbook.common.email.port.EmailResource:sendEmail() per minute",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "catalogController_seconds_max{pod=\"$instance\"}",
     "legendFormat": "Seconds consumed by getAll per minute"
    }
   ]
  }
 ]
}