---
# Source: application/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  namespace: NAMESPACE
  labels:
    app: catalog    
  name: catalog
spec:
  selector:
    app: catalog
  ports:
    - name: https
      port: 8080
      targetPort: 8080
    
---
# Source: application/templates/deployment.yaml

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: NAMESPACE
  labels:
    app: catalog    
  name: catalog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog        
    spec:
      containers:
      - name: catalog
        image: "stakater/stakater-nordmart-catalog:v0.0.1"
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql_password
                name: mysql-secret
          - name: MYSQL_HOST
            value: mysql-svc.NAMESPACE.svc
          - name: MYSQL_DB_NAME
            value: catalog
          
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        
      serviceAccountName: default