apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-role-binding
  labels:
    app: prometheus-operator-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-cluster-role
subjects:
  - kind: ServiceAccount
    name: sa
    namespace: NAMESPACE
