# Source: prometheus-operator/charts/grafana/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: NAMESPACE-grafana
  namespace: NAMESPACE
  labels:
    app: grafana
    chart: grafana-4.0.2
    heritage: Tiller
    release: NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: NAMESPACE-grafana
subjects:
- kind: ServiceAccount
  name: NAMESPACE-grafana
  namespace: NAMESPACE
