apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    prometheus: grafana-NAMESPACE
  name: route-grafana
  namespace: NAMESPACE
spec:
  host: grafana-NAMESPACE.cp-stakater.com
  port:
    targetPort: web
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: NAMESPACE-grafana
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - host: grafana-NAMESPACE.cp-stakater.com
      routerName: router
      wildcardPolicy: None