# Source: prometheus-operator/charts/grafana/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: NAMESPACE-grafana
  namespace: NAMESPACE
  labels:
    app: grafana
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "c3Rha2F0ZXI="
  ldap-toml: ""