# Source: prometheus-operator/charts/grafana/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: grafana
    chart: grafana-4.0.2
    heritage: Tiller
    release: participant-3
  name: participant-3-grafana
  namespace: participant-3
