# Source: prometheus-operator/charts/grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: NAMESPACE-grafana
  namespace: NAMESPACE
  labels:
    app: grafana
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana