apiVersion: authorization.openshift.io/v1
groupNames: []
kind: ClusterRoleBinding
metadata:
  name: prometheus-NAMESPACE
  namespace: NAMESPACE
roleRef:
  kind: ClusterRole
  name: prometheus-NAMESPACE
subjects:
- kind: ServiceAccount
  name: prometheus-NAMESPACE
  namespace: NAMESPACE
userNames:
- system:serviceaccount:NAMESPACE:prometheus-NAMESPACE
