apiVersion: v1
data:
  session_secret: R2dSK3lVK2VxNmpxQVNMS2t0MnY4dVRXSUZhbVlSKzBMYzMrTDdlT2djZDZWbzBCQW5DM1I5Q2xOZz09
kind: Secret
metadata:
  name: prometheus-proxy
  namespace: NAMESPACE
type: Opaque