apiVersion: authorization.openshift.io/v1
groupNames: []
kind: RoleBinding
metadata:
  name: prometheus-NAMESPACE
  namespace: NAMESPACE
roleRef:
  kind: Role
  name: prometheus-NAMESPACE
subjects:
- kind: ServiceAccount
  name: prometheus-NAMESPACE
  namespace: NAMESPACE
userNames:
- system:serviceaccount:NAMESPACE:prometheus-NAMESPACE
