apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    prometheus: prometheus-NAMESPACE
  name: prometheus-NAMESPACE
  namespace: NAMESPACE
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: web
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: prometheus
    prometheus: prometheus-NAMESPACE