apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2019-12-06T07:54:24Z"
  generation: 1
  labels:
    k8s-app: kube-state-metrics
  name: kube-state-metrics
  namespace: openshift-monitoring
  resourceVersion: "37397"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/openshift-monitoring/servicemonitors/kube-state-metrics
  uid: 9e6d133c-17fd-11ea-a063-000d3aa92502
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 2m
    port: https-main
    scheme: https
    scrapeTimeout: 2m
    targetPort: 0
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      serverName: kube-state-metrics.openshift-monitoring.svc
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 2m
    port: https-self
    scheme: https
    scrapeTimeout: 2m
    targetPort: 0
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      serverName: kube-state-metrics.openshift-monitoring.svc
  jobLabel: k8s-app
  namespaceSelector: {}
  selector:
    matchLabels:
      k8s-app: kube-state-metrics
